server:
  port: 9527
spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由功能
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://PROVIDER-PAYMENT
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由

eureka:
  instance:
    instance-id: provider-gateway-9527
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
