server:
  port: 8004

spring:
  application:
    name: provider-payment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudv2?serverTimezone=UTC
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eryi.pojo

eureka:
  instance:
    instance-id: provider-payment-hystrix-8004
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

