server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
      stream:
        binders:
          #自定义的配置
          defaultRabbit:  #此次配置的名称为defaultRabbit
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: 127.0.0.1
                  port: 5672
                  username: guest
                  password: guest
      bindings:
        output: #output表示为发送者
          destination: studyExchange #通道名称
          content-type: application/json #消息类型，json
          binder: defaultRabbit #绑定配置

eureka:
  instance:
    instance-id: provider-payment-8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

