server:
  port: 80

spring:
  application:
    name: conusmer-order-80
eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/, http://127.0.0.1:7002/eureka/


ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000

logging:
  level:
    com.eryi.service.PaymentService: debug